podTemplate(label: 'mypod',
    volumes: [
        hostPathVolume(hostPath: '/var/run/docker.sock', mountPath: '/var/run/docker.sock'),
        secretVolume(secretName: 'icpadmin', mountPath: '/var/run/secrets/registry-account'),
        configMapVolume(configMapName: 'icpconfig', mountPath: '/var/run/configs/registry-config')
    ],
    containers: [
        containerTemplate(name: 'kubectl', image: 'ibmcloudacademy/k8s-icp:v1.0', ttyEnabled: true, command: 'cat'),
  ]) {

    node('mypod') {
        checkout scm
        container('kubectl') {
            stage('Deploy new Docker Image') {
                sh """
                #!/bin/bash
                set +e
                NAMESPACE=`cat /var/run/configs/registry-config/namespace`
                REGISTRY=`cat /var/run/configs/registry-config/registry`
		DOCKER_USER=`cat /var/run/secrets/registry-account/username`
		DOCKER_PASSWORD=`cat /var/run/secrets/registry-account/password`

                wget --no-check-certificate https://10.10.1.10:8443/api/cli/icp-linux-amd64
		whoami
		set
                bx plugin install icp-linux-amd64
                helm init --client-only
                bx pr login -a https://10.10.1.10:8443 --skip-ssl-validation -u \${DOCKER_USER} -p \${DOCKER_PASSWORD} -c id-cloudcluster-account
                bx pr cluster-config cloudcluster
                helm version -s --tls
		cd charts
		helm package ibmcase-couchdb
		helm index .

                # helm repo add https://raw.githubusercontent.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes/master/docs/charts
                helm install --tls -n bluecompute-couchdb ibmcase-couchdb
                """
            }
        }
    }
}
